# Site settings
title: Nicole Jiang
email: nicolekjiang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nicole Jiang is a Computer Engineering student from University of Waterloo; Product Designer previously at Palantir Technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nicolejiang.com" # the base hostname & protocol for your site
twitter_username: nicolekjiang
github_username:  nicolekjiang

# Build settings
markdown: kramdown

# Site settings
url: localhost:4000 